"""Turn a character's levels.json into LDraw (.ldr) minifig files, one per level.

Usage:  python build_ldr.py ../characters/warrior/levels.json ../ldr
LDraw units (LDU): -Y is up, 20 LDU = one stud, minifig torso origin = neck.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COLORS = json.loads((ROOT / "catalog" / "slots.json").read_text())["ldraw_colors"]

I = "1 0 0 0 1 0 0 0 1"  # identity rotation
# Hand frames copied from the LDraw torso shortcuts (76382pXX).
HAND_R = "0.985 -0.12 0.12 0.17 0.696 -0.696 0 0.707 0.707"
HAND_L = "0.985 0.12 -0.12 -0.17 0.696 -0.696 0 0.707 0.707"
# Where a held item's grip sits (hand position + grip offset along the hand frame).
GRIP_R = (-24.89, 33.73, -9.898)
GRIP_L = (24.89, 33.73, -9.898)


def col(name):
    return COLORS[name]


def line(color, pos, rot, part):
    x, y, z = pos
    return f"1 {col(color)} {x:g} {y:g} {z:g} {rot} {part}.dat"


def torso_lines(t):
    if "arms" in t:  # torso (973 or a printed 973pXX) assembled piece by piece so arms/hands get their own colours
        return [
            line(t["color"], (0, 0, 0), I, t["part"]),
            line(t["arms"], (-15.552, 9, 0), "0.985 -0.17 0 0.17 0.985 0 0 0 1", "3818"),
            line(t["arms"], (15.552, 9, 0), "0.985 0.17 0 -0.17 0.985 0 0 0 1", "3819"),
            line(t["hands"], (-23.69, 26.774, -9.898), HAND_R, "3820"),
            line(t["hands"], (23.69, 26.774, -9.898), HAND_L, "3820"),
        ]
    return [line(t["color"], (0, 0, 0), I, t["part"])]


def build(level, character):
    out = [
        f"0 {character.title()} - Level {level['level']} {level['title']}",
        f"0 Name: {character}_L{level['level']}.ldr",
        "0 Author: Solo Leveling (generated by tools/build_ldr.py)",
        "0 // head",
        line(level["head"]["color"], (0, -24, 0), I, level["head"]["part"]),
        "0 // hair / helmet",
        line(level["hair"]["color"], (0, -24, 0), I, level["hair"]["part"]),
        "0 // torso",
        *torso_lines(level["torso"]),
        "0 // legs",
        line(level["legs"]["color"], (0, 32, 0), I, level["legs"]["part"]),
    ]
    g = level.get("gear", {})
    if "neck" in g:
        out += ["0 // gear: neck", line(g["neck"]["color"], (0, 0, 0), I, g["neck"]["part"])]
    if "right_hand" in g:
        out += ["0 // gear: right hand", line(g["right_hand"]["color"], GRIP_R, HAND_R, g["right_hand"]["part"])]
    if "left_hand" in g:
        out += ["0 // gear: left hand", line(g["left_hand"]["color"], GRIP_L, HAND_L, g["left_hand"]["part"])]
    s = level["shoes"]
    out.append(f"0 !SHOES {s['color']} {s['finish']}")  # applied in Blender (foot area of the legs)
    return "\n".join(out) + "\n"


def main(levels_path, out_dir):
    data = json.loads(Path(levels_path).read_text())
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for lv in data["levels"]:
        p = out_dir / f"{data['character']}_L{lv['level']}.ldr"
        p.write_text(build(lv, data["character"]))
        print("wrote", p.name)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
